version: '3'
services:
    app:
        container_name: zid-app
        restart: unless-stopped
        build:
          context: .
          dockerfile: Dockerfile
        environment:
            - PHP_UPLOAD_MAX_FILESIZE=200M
            - PHP_POST_MAX_SIZE=200M
            - SERVICE_NGINX_CLIENT_MAX_BODY_SIZE=200M
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        networks:
            - zid-network
        ports:
            - '${APP_PORT:-8000}:80'
        depends_on:
            - db
        volumes:
            - .:/app
    db:
        container_name: zid-db
        restart: unless-stopped
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - zid-data:/var/lib/mysql
        networks:
            - zid-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    zid-network:
        driver: bridge

volumes:
  zid-data:
